version: "3.0"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"
  java:
    image: eclipse-temurin:21-jre
    container_name: java-app-containe
    working_dir: /app
    volumes:
      - ./build/libs:/app
    environment:
      - TZ=Asia/Seoul
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    command: [ "java", "-jar", "TodoList.jar" ]
    depends_on:
      - mariadb
    ports:
      - "8080:8080"